site_name: Rewatch Docs
site_url: https://rewatch.kirilov.dev
site_description: "User guide and reference for Rewatch"
repo_url: https://github.com/EdinUser/YouTubeLocalHistory
docs_dir: docs
theme:
  name: material
  logo: assets/icon128.png
  favicon: assets/icon128.png
plugins:
  - search
  - macros
nav:
  - Home: index.md
  - Detailed Guide: detailed_guide.md
  - Changelog: ../CHANGELOG.md
  - FAQ: faq.md
  - Technical: technical.md
  - Build: build.md
  - Testing: testing.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
  - Live chat: https://t.me/+eFftKWGVvSpiZjZk
  - Community: https://community.kirilov.dev/t/re-watch
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list

