site_name: Rewatch Docs
site_url: https://rewatch.kirilov.dev
site_description: "User guide and reference for Rewatch"
docs_dir: docs
theme:
  name: custommill
  logo: assets/icon128.png
  favicon: assets/icon128.png
plugins:
  - search
  - macros
nav:
  - Home: index.md
  - Detailed Guide: detailed_guide.md
  - FAQ: faq.md
  - Technical: technical.md
  - Build: build.md
  - Testing: testing.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
  - README: readme.md
  - Changelog: ../CHANGELOG.md
  - Community: https://t.me/+eFftKWGVvSpiZjZk
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list

